A# Ramona Bendias, Eda Dagasan

# Task 1

In [2]:
import numpy as np
import scipy.linalg as la


class Orthogonalization():
    """
    A class of matrices with methods that orthogonalize the objects with
    different algorithms and that evaluate the result in different ways.
    """
    
    def __init__(self, givenmatrix):
        self.givenmatrix = givenmatrix
    
    def gramschmidt(self):
        """
        Gram-Schmidt orthogonalization of an object of the class. 
        The method returns a matrice 'orthogonalmatrix' that is an 
        orthogonal basis of range(A).
        """
        n = len(self.givenmatrix[0])
        m = len(self.givenmatrix)
        trianglematrix = np.zeros(shape=(n,n))
        orthogonalmatrix = np.array(np.zeros(shape=(self.givenmatrix.shape)))
        v = np.zeros(shape=(n,n))
        for j in range(n):
            v[j] = self.givenmatrix[j]
            for i in range(j-1):
                trianglematrix[i][j] = np.dot(orthogonalmatrix[i],self.givenmatrix[j])
                v[j] = v[j] - trianglematrix[i][j]*orthogonalmatrix[i]
            trianglematrix[j][j] = la.norm(v[j])
            orthogonalmatrix[j] = np.divide(v[j],trianglematrix[j][j])

        return orthogonalmatrix
   
    def norm(self, matrix):
        """
        Returns the 2-norm of a the input matrix A.
        """
        return np.linalg.norm(matrix, ord=2)
        
        
    def qtq(self, matrix):
        """
        Returns the matrix product of the transpose of the input matrix A with
        itself.
        """
        return np.dot(matrix.transpose(),matrix)
        
    def deviation(self, matrix):
        """
        Returns the deviation of the output matrix of qtq from the identity 
        matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return self.norm(I-qtq)
        
    def allclose(self, matrix):
        """
        Returns True/False if all the entries of QTQ are closer than a 
        certain tolerance to the identity matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return np.allclose(qtq, I)
        
    def eigenvalues(self, matrix):
        """
        Returns an array with the eigenvalues of qtq of the input matrix A.
        """
        return la.eigvals(self.qtq(matrix))
    
    def determinant(self, matrix):
        """
        Returns the determinant of qtq of the input matrix A.
        """
        return la.det(self.qtq(matrix))

In [3]:
A0 = np.random.rand(4,4)
print('Random matrix', A0)
A = Orthogonalization(A0)
V = A.gramschmidt()
print('Orthogonalized matrix', V)

Random matrix [[ 0.43497842  0.9388841   0.43026994  0.80882054]
 [ 0.17754918  0.73005302  0.87184522  0.25520397]
 [ 0.29745454  0.16620749  0.22007574  0.29290153]
 [ 0.21082613  0.30496243  0.04712944  0.11126076]]
Orthogonalized matrix [[ 0.31473666  0.67934692  0.31132976  0.58523703]
 [ 0.15060911  0.61927986  0.7395575   0.21648109]
 [ 0.69493945 -0.60709241  0.35902741  0.13999032]
 [ 0.17184164 -0.32318593 -0.80544645 -0.46613016]]


# Task 2

In [29]:
def test(m,n):
    '''
    Return Testvalues with which you can see how good the Gramschmidt factorization is
    '''
    matrix = np.random.rand(m,n)
    QR = Orthogonalization(matrix)
    norm = QR.norm(QR.gramschmidt())
    eigenvalues = QR.eigenvalues(QR.qtq(QR.gramschmidt()))
    determinant = QR.determinant(QR.qtq(QR.gramschmidt()))
    deviation = QR.deviation(QR.qtq(QR.gramschmidt()))
    
    return "The two norm of the orthorganal matrix should be 1 and is: {}, the deviation of the QTQ and I is: {}, the eigenvalues of the QTQ are: {} and the determinat of the same matrix is: {}".format(norm, deviation, eigenvalues, determinant)
        





In [30]:
test(3,3)

'The two norm of the orthorganal matrix should be 1 and is: 1.3462001768727594, the deviation of the QTQ and I is: 2.284267881335465, the eigenvalues of the QTQ are: [ 3.28426788+0.j  0.03524822+0.j  1.00000000+0.j] and the determinat of the same matrix is: 0.1157645852808725'

# Task 3

In [14]:
B,S = la.qr(A0)

print('Triangular matrix:', S)
print('B@S',B@S)
print('Norm B:', A.norm(B))
print('Dev of BTB from I:', A.deviation(B))
print('BtB close to I?', A.allclose(B))
print('Eigenvalues of BTB:', A.eigenvalues(B))
print('Determinant of BTB:', A.determinant(B))

Triangular matrix: [[-0.84586696 -1.1982873  -0.78918292 -0.53369087]
 [ 0.         -0.47659756  0.27506307 -0.36084838]
 [ 0.          0.         -0.45658428 -0.59754839]
 [ 0.          0.          0.         -0.29355005]]
B@S [[ 0.71817933  0.80297935  0.66760897  0.12034719]
 [ 0.07478469  0.16089319  0.04697639  0.39083824]
 [ 0.19026435  0.19110106  0.66118018  0.62857187]
 [ 0.3973866   0.97767869  0.1478879   0.5439969 ]]
Norm B: 1.0
Dev of BTB from I: 4.99839120305e-16
BtB close to I? True
Eigenvalues of BTB: [ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
Determinant of BTB: 1.0


# Task 4

In [23]:
import numpy as np
import scipy.linalg as la


class Orthogonalization():
    """
    A class of matrices with methods that orthogonalize the objects with
    different algorithms and that evaluate the result in different ways.
    """
    
    def __init__(self, givenmatrix):
        self.givenmatrix = givenmatrix
        
    def householder(self):
        """
        Will not work with a already triangular matrix (:
        """
        A = self.givenmatrix
        m = shape(A)[0]
        n = shape(A)[1]
        Q = identity(m)
        for i in range(n):
            Q_i = identity(m)
            x = A[i:m,i]
            s = int(sign(x[0]))
            u = s*array([norm(x)]+(m-i-1)*[0.]) 
            v_i = x + u
            v_i /= norm(v_i)
            Q_i_hat = eye(m-i) - 2*outer(v_i,v_i)
            Q_i[i:m,i:m] = Q_i_hat
            Q = Q_i@Q
            A = Q_i@A
        return Q, A
        
    def norm(self, matrix):
        """
        Returns the 2-norm of a the input matrix A.
        """
        return np.linalg.norm(matrix, ord=2)
        
        
    def qtq(self, matrix):
        """
        Returns the matrix product of the transpose of the input matrix A with
        itself.
        """
        return np.dot(matrix.transpose(),matrix)
        
    def deviation(self, matrix):
        """
        Returns the deviation of the output matrix of qtq from the identity 
        matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return self.norm(I-qtq)
        
    def allclose(self, matrix):
        """
        Returns True/False if all the entries of QTQ are closer than a 
        certain tolerance to the identity matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return np.allclose(qtq, I)
        
    def eigenvalues(self, matrix):
        """
        Returns an array with the eigenvalues of qtq of the input matrix A.
        """
        return la.eigvals(self.qtq(matrix))
    
    def determinant(self, matrix):
        """
        Returns the determinant of qtq of the input matrix A.
        """
        return la.det(self.qtq(matrix))

A0 = np.random.rand(4,4)
print('Random matrix', A0)
A = Orthogonalization(A0)

Q,R = A.householder()
print('Triangular matrix:', R)
print('Q@R:', Q@R)
print('Norm of Q:', A.norm(Q))
print('Deviation of QTQ from I:', A.deviation(Q))
print('QTQ allclose to I?', A.allclose(Q))
print('Eigenvalues of QTQ:', A.eigenvalues(Q))
print('Determinant of QTQ:', A.determinant(Q))

Random matrix [[ 0.402023    0.93459562  0.45279827  0.27279716]
 [ 0.16135381  0.84871248  0.68668706  0.50635793]
 [ 0.20793518  0.93917365  0.39871541  0.89684444]
 [ 0.04216666  0.8315532   0.36631435  0.46161104]]
Triangular matrix: [[ -4.82361495e-01  -1.54038621e+00  -8.10985355e-01  -8.23705099e-01]
 [  1.53350146e-17  -8.91358543e-01  -4.88945096e-01  -7.20282715e-01]
 [ -5.39708042e-18   1.83429723e-16   2.70112996e-01  -8.24821645e-02]
 [ -7.13154163e-18   3.19417538e-17  -2.77555756e-17   3.79645558e-01]]
Q@R: [[ 0.402023    1.58199771  0.72303019  0.92982404]
 [-0.18898988 -0.2700845  -0.21821923 -0.32464425]
 [ 0.05633435 -0.58733979 -0.4279585  -0.61477195]
 [ 0.17933039  0.4966682   0.4649568  -0.0178928 ]]
Norm of Q: 1.0
Deviation of QTQ from I: 6.99871496271e-16
QTQ allclose to I? True
Eigenvalues of QTQ: [ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
Determinant of QTQ: 1.0000000000000007


# Task 5

In [26]:
import numpy as np
import scipy.linalg as la


class Orthogonalization():
    """
    A class of matrices with methods that orthogonalize the objects with
    different algorithms and that evaluate the result in different ways.
    """
    
    def __init__(self, givenmatrix):
        self.givenmatrix = givenmatrix
        
    def givens(self):
        """
        Takes a (mxn)-matrix with m≥n and returns its QR-factorization as the
        two matrices Q, A, by using Givens rotations.
        """
        A = self.givenmatrix
        m = shape(A)[0]
        n = shape(A)[1]
        Q = identity(m)
        for i in range(n): #counting through the columns of the matrix
            Q_i = identity(m)
            x = A[i:m,i]
            l = len(x)
            Q_i_hat = identity(l)
            for j in range(l-1):
                J_j = identity(l) #rotation matrix to be
                a = x[l-(j+2)]
                b = x[l-(j+1)]
                r = sqrt(a**2+b**2)
                c = a/r
                s = -b/r
                rotation = array([[c, -s], [s, c]])
                J_j[l-2-j:l-j, l-2-j:l-j] = rotation #rotation matrix in the 
                                                    #(n-(i-1), n-i)-plane
                
                Q_i_hat = J_j@Q_i_hat #matrix for all the rotations of one vector
            Q_i[i:m,i:m] = Q_i_hat
            Q = Q_i@Q
            A = Q_i@A
        return Q, A
        
    def norm(self, matrix):
        """
        Returns the 2-norm of a the input matrix A.
        """
        return np.linalg.norm(matrix, ord=2)
        
        
    def qtq(self, matrix):
        """
        Returns the matrix product of the transpose of the input matrix A with
        itself.
        """
        return np.dot(matrix.transpose(),matrix)
        
    def deviation(self, matrix):
        """
        Returns the deviation of the output matrix of qtq from the identity 
        matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return self.norm(I-qtq)
        
    def allclose(self, matrix):
        """
        Returns True/False if all the entries of QTQ are closer than a 
        certain tolerance to the identity matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return np.allclose(qtq, I)
        
    def eigenvalues(self, matrix):
        """
        Returns an array with the eigenvalues of qtq of the input matrix A.
        """
        return la.eigvals(self.qtq(matrix))
    
    def determinant(self, matrix):
        """
        Returns the determinant of qtq of the input matrix A.
        """
        return la.det(self.qtq(matrix))

A0 = np.random.rand(4,4)
print('Random matrix', A0)
A = Orthogonalization(A0)

q,r = A.givens()
print('Triangular matrix:', r)
print('q@r:',q@r)
print('Norm:', A.norm(q))
print('Deviation from I of qtq:', A.deviation(q))
print('Qtq allclose to I?', A.allclose(q))
print('Eigenvalues of qtq:', A.eigenvalues(q))
print('Determinant of qtq:', A.determinant(q))

Random matrix [[ 0.63047837  0.16193227  0.27741012  0.47655692]
 [ 0.08327226  0.32409549  0.83467416  0.52361767]
 [ 0.52792633  0.34199413  0.61118677  0.23953597]
 [ 0.79023356  0.81979877  0.22666604  0.44697969]]
Triangular matrix: [[ 0.74966945  0.27989116  0.36034183  0.5484195 ]
 [ 0.85264977  0.81239686  0.5386989   0.42935593]
 [ 0.01895898  0.19469265  0.88233857  0.43980411]
 [-0.13504507 -0.37954844  0.         -0.28268741]]
q@r: [[ 0.7474486   0.26722404  0.43162555  0.55365428]
 [-0.18070147 -0.18518276  0.53883784  0.01284418]
 [ 0.82579939  0.89779583  0.72882464  0.57666333]
 [-0.18529831  0.09247311  0.43672863  0.34527041]]
Norm: 1.0
Deviation from I of qtq: 2.78284930478e-16
Qtq allclose to I? True
Eigenvalues of qtq: [ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
Determinant of qtq: 0.9999999999999994
