A# Ramona Bendias, Eda Dagasan

# Task 1

In [2]:
import numpy as np
import scipy.linalg as la


class Orthogonalization():
    """
    A class of matrices with methods that orthogonalize the objects with
    different algorithms and that evaluate the result in different ways.
    """
    
    def __init__(self, givenmatrix):
        self.givenmatrix = givenmatrix
    
    def gramschmidt(self):
        """
        Gram-Schmidt orthogonalization of an object of the class. 
        The method returns a matrice 'orthogonalmatrix' that is an 
        orthogonal basis of range(A).
        """
        n = len(self.givenmatrix[0])
        m = len(self.givenmatrix)
        trianglematrix = np.zeros(shape=(n,n))
        orthogonalmatrix = np.array(np.zeros(shape=(self.givenmatrix.shape)))
        for j in range(n):
            v_j = self.givenmatrix[:,j] #j:th column
            for i in range(j):
                q_i = orthogonalmatrix[:,i] #i:th column
                r_ij = dot(q_i,v_j)
                v_j -= r_ij*q_i
                trianglematrix[i][j] = r_ij
            r_jj = norm(v_j)
            trianglematrix[j][j] = r_jj
            q_j = v_j/r_jj
            orthogonalmatrix[:,j] = q_j

        return orthogonalmatrix, trianglematrix
   
    def norm(self, matrix):
        """
        Returns the 2-norm of a the input matrix A.
        """
        return np.linalg.norm(matrix, ord=2)
        
        
    def qtq(self, matrix):
        """
        Returns the matrix product of the transpose of the input matrix A with
        itself.
        """
        return np.dot(matrix.transpose(),matrix)
        
    def deviation(self, matrix):
        """
        Returns the deviation of the output matrix of qtq from the identity 
        matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return self.norm(I-qtq)
        
    def allclose(self, matrix):
        """
        Returns True/False if all the entries of QTQ are closer than a 
        certain tolerance to the identity matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return np.allclose(qtq, I)
        
    def eigenvalues(self, matrix):
        """
        Returns an array with the eigenvalues of qtq of the input matrix A.
        """
        return la.eigvals(self.qtq(matrix))
    
    def determinant(self, matrix):
        """
        Returns the determinant of qtq of the input matrix A.
        """
        return la.det(self.qtq(matrix))

In [3]:
A0 = np.random.rand(4,4)
print('Random matrix', A0)
A = Orthogonalization(A0)
V = A.gramschmidt()
print('Orthogonalized matrix', V)

Random matrix [[ 0.43497842  0.9388841   0.43026994  0.80882054]
 [ 0.17754918  0.73005302  0.87184522  0.25520397]
 [ 0.29745454  0.16620749  0.22007574  0.29290153]
 [ 0.21082613  0.30496243  0.04712944  0.11126076]]
Orthogonalized matrix [[ 0.31473666  0.67934692  0.31132976  0.58523703]
 [ 0.15060911  0.61927986  0.7395575   0.21648109]
 [ 0.69493945 -0.60709241  0.35902741  0.13999032]
 [ 0.17184164 -0.32318593 -0.80544645 -0.46613016]]


# Task 2

In [38]:
def test(m,n, eigenvalues=None):
    '''
    @param m: integer which gives the number of rows 
    @param n: integer which gives the number of columns
    Creates a random matrix with the shape mxn and returns after the gramschmidt factorisation characteristic values of Q and QTQ. 
    '''
    matrix = np.random.rand(m,n)
    QR = Orthogonalization(matrix)
    norm = QR.norm(QR.gramschmidt()[0])
    if eigenvalues:
        eigenvalues = QR.eigenvalues(QR.qtq(QR.gramschmidt()[0]))
    else: 
        eigenvalues = "not calculated  (To calculat them add e.g. a number to the input)"
    determinant = QR.determinant(QR.qtq(QR.gramschmidt()[0]))
    deviation = QR.deviation(QR.qtq(QR.gramschmidt()[0]))
    
    return "The two norm of the orthorganal matrix should be 1 and is: {}, the deviation of the QTQ and I is: {}, the eigenvalues of the QTQ are: {} and the determinat of the same matrix is: {}".format(norm, deviation, eigenvalues, determinant)

In [45]:
test(1000,1000)

'The two norm of the orthorganal matrix should be 1 and is: 31.582920120779637, the deviation of the QTQ and I is: 994967.0328612943, the eigenvalues of the QTQ are: not calculated  (To calculat them add a number to the input) and the determinat of the same matrix is: 0.0'

In [46]:
test(5,5,1)

'The two norm of the orthorganal matrix should be 1 and is: 1.8504294963586974, the deviation of the QTQ and I is: 10.724387678147224, the eigenvalues of the QTQ are: [  1.17243877e+01+0.j   1.16443753e+00+0.j   1.53120792e-01+0.j\n   8.83812455e-03+0.j   1.32291279e-04+0.j] and the determinat of the same matrix is: 2.4441725584033355e-06'

The values of the test shouldn't be like they are. The norm of the Orthogonalmatrix should be 1 and is complete different. There is no rules e.g the bigger the matrix is the bigger the norm gets. The deviation of the QTQ from the identidymatrix is very high and if we use the numpy command allclose it is always FALSE, which means that the deviation is two big (measured by standard tolerance setting of numpy). Also the eigenvalues are not always 1 or -1, this is the same for the determinat. 

# Task 3

In [14]:
B,S = la.qr(A0)

print('Triangular matrix:', S)
print('B@S',B@S)
print('Norm B:', A.norm(B))
print('Dev of BTB from I:', A.deviation(B))
print('BtB close to I?', A.allclose(B))
print('Eigenvalues of BTB:', A.eigenvalues(B))
print('Determinant of BTB:', A.determinant(B))

Triangular matrix: [[-0.84586696 -1.1982873  -0.78918292 -0.53369087]
 [ 0.         -0.47659756  0.27506307 -0.36084838]
 [ 0.          0.         -0.45658428 -0.59754839]
 [ 0.          0.          0.         -0.29355005]]
B@S [[ 0.71817933  0.80297935  0.66760897  0.12034719]
 [ 0.07478469  0.16089319  0.04697639  0.39083824]
 [ 0.19026435  0.19110106  0.66118018  0.62857187]
 [ 0.3973866   0.97767869  0.1478879   0.5439969 ]]
Norm B: 1.0
Dev of BTB from I: 4.99839120305e-16
BtB close to I? True
Eigenvalues of BTB: [ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
Determinant of BTB: 1.0


# Task 4

In [4]:
from numpy import *
from scipy.linalg import *


class Orthogonalization():
    """
    A class of matrices with methods that orthogonalize the objects with
    different algorithms and that evaluate the result in different ways.
    """
    
    def __init__(self, givenmatrix):
        self.givenmatrix = givenmatrix
        
    def householder(self):
        """
        Will not work with a already triangular matrix (:
        """
        A = self.givenmatrix
        m = shape(A)[0]
        n = shape(A)[1]
        Q = identity(m)
        for i in range(n):
            Q_i = identity(m)
            x = A[i:m,i] 
            s = int(sign(x[0]))
            u = s*array([norm(x)]+(m-i-1)*[0.]) 
            v_i = x + u
            v_i /= norm(v_i)
            Q_i_hat = eye(m-i) - 2*outer(v_i,v_i)
            Q_i[i:m,i:m] = Q_i_hat
            Q = Q_i@Q
            A = Q_i@A
        return Q.T, A #the construction gives "Q.T" not the Q we searched
    
    def norm(self, matrix):
        """
        Returns the 2-norm of a the input matrix A.
        """
        return np.linalg.norm(matrix, ord=2)
        
        
    def qtq(self, matrix):
        """
        Returns the matrix product of the transpose of the input matrix A with
        itself.
        """
        return np.dot(matrix.transpose(),matrix)
        
    def deviation(self, matrix):
        """
        Returns the deviation of the output matrix of qtq from the identity 
        matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return self.norm(I-qtq)
        
    def allclose(self, matrix):
        """
        Returns True/False if all the entries of QTQ are closer than a 
        certain tolerance to the identity matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return np.allclose(qtq, I)
        
    def eigenvalues(self, matrix):
        """
        Returns an array with the eigenvalues of qtq of the input matrix A.
        """
        return la.eigvals(self.qtq(matrix))
    
    def determinant(self, matrix):
        """
        Returns the determinant of qtq of the input matrix A.
        """
        return la.det(self.qtq(matrix))

A0 = np.random.rand(4,4)
print('Random matrix', A0)
A = Orthogonalization(A0)

Q,R = A.householder()
print('Triangular matrix:', R)
print('Q@R:', Q@R)
print('Norm of Q:', A.norm(Q))
print('Deviation of QTQ from I:', A.deviation(Q))
print('QTQ allclose to I?', A.allclose(Q))
print('Eigenvalues of QTQ:', A.eigenvalues(Q))
print('Determinant of QTQ:', A.determinant(Q))

Random matrix [[ 0.14994376  0.88803281  0.13777488  0.0172822 ]
 [ 0.35435615  0.95555843  0.29265608  0.99472686]
 [ 0.36370066  0.51623014  0.04007999  0.90081203]
 [ 0.66516379  0.74622762  0.9971199   0.48996343]]
Triangular matrix: [[ -8.50160247e-01  -1.35960229e+00  -9.43572859e-01  -1.18637728e+00]
 [  1.01623213e-17  -8.22511411e-01   1.41172891e-01  -2.23116783e-01]
 [ -2.57641611e-17  -1.93304279e-17   4.36147315e-01  -6.18563063e-01]
 [  1.81857214e-18   8.09918660e-17   1.38777878e-17  -4.48792014e-01]]
Q@R: [[ 0.14994376  0.88803281  0.13777488  0.0172822 ]
 [ 0.35435615  0.95555843  0.29265608  0.99472686]
 [ 0.36370066  0.51623014  0.04007999  0.90081203]
 [ 0.66516379  0.74622762  0.9971199   0.48996343]]
Norm of Q: 1.0
Deviation of QTQ from I: 7.11482023488e-16
QTQ allclose to I? True
Eigenvalues of QTQ: [ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
Determinant of QTQ: 1.0000000000000013


# Task 5

In [6]:
class Orthogonalization():
    """
    A class of matrices with methods that orthogonalize the objects with
    different algorithms and that evaluate the result in different ways.
    """
    
    def __init__(self, givenmatrix):
        self.givenmatrix = givenmatrix
        
    def givens(self):
        """
        Takes a (mxn)-matrix with m≥n and returns its QR-factorization as the
        two matrices Q, A, by using Givens rotations.
        """
        A = self.givenmatrix
        m = shape(A)[0]
        n = shape(A)[1]
        Q = identity(m)
        for i in range(n): #counting through the columns of the matrix
            Q_i = identity(m)
            x = A[i:m,i]
            l = len(x)
            Q_i_hat = identity(l)
            for j in range(l-1):
                J_j = identity(l) #rotation matrix to be
                a = x[l-(j+2)]
                b = x[l-(j+1)]
                r = sqrt(a**2+b**2)
                c = a/r
                s = -b/r
                rotation = array([[c, -s], [s, c]])
                J_j[l-2-j:l-j, l-2-j:l-j] = rotation #rotation matrix in the 
                                                    #(n-(i-1), n-i)-plane
                
                Q_i_hat = J_j@Q_i_hat #matrix for all the rotations of one vector
            Q_i[i:m,i:m] = Q_i_hat
            Q = Q_i@Q
            A = Q_i@A
        return Q.T, A
        
    def norm(self, matrix):
        """
        Returns the 2-norm of a the input matrix A.
        """
        return np.linalg.norm(matrix, ord=2)
        
        
    def qtq(self, matrix):
        """
        Returns the matrix product of the transpose of the input matrix A with
        itself.
        """
        return np.dot(matrix.transpose(),matrix)
        
    def deviation(self, matrix):
        """
        Returns the deviation of the output matrix of qtq from the identity 
        matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return self.norm(I-qtq)
        
    def allclose(self, matrix):
        """
        Returns True/False if all the entries of QTQ are closer than a 
        certain tolerance to the identity matrix.
        """
        qtq = self.qtq(matrix)
        I = np.identity(len(qtq))
        return np.allclose(qtq, I)
        
    def eigenvalues(self, matrix):
        """
        Returns an array with the eigenvalues of qtq of the input matrix A.
        """
        return la.eigvals(self.qtq(matrix))
    
    def determinant(self, matrix):
        """
        Returns the determinant of qtq of the input matrix A.
        """
        return la.det(self.qtq(matrix))

A0 = np.random.rand(4,4)
print('Random matrix', A0)
A = Orthogonalization(A0)

q,r = A.givens()
print('Triangular matrix:', r)
print('q@r:',q@r)
print('Norm:', A.norm(q))
print('Deviation from I of qtq:', A.deviation(q))
print('Qtq allclose to I?', A.allclose(q))
print('Eigenvalues of qtq:', A.eigenvalues(q))
print('Determinant of qtq:', A.determinant(q))

Random matrix [[ 0.29847214  0.18381257  0.63260693  0.32095855]
 [ 0.88355969  0.39749837  0.75586749  0.6847201 ]
 [ 0.19932305  0.89078701  0.7322677   0.60840769]
 [ 0.40702311  0.98530837  0.49158964  0.22882183]]
Triangular matrix: [[  1.00657856e+00   6.92356020e-01   1.06020604e+00   8.34155453e-01]
 [  2.36826001e-01   1.21522238e+00   6.73711987e-01   4.28662736e-01]
 [ -5.79990806e-02   1.56781637e-03   4.14100066e-01   2.54600627e-01]
 [  5.00997177e-02   1.15930078e-03   0.00000000e+00  -2.23577317e-01]]
q@r: [[ 0.29847214  0.18381257  0.63260693  0.32095855]
 [ 0.88355969  0.39749837  0.75586749  0.6847201 ]
 [ 0.19932305  0.89078701  0.7322677   0.60840769]
 [ 0.40702311  0.98530837  0.49158964  0.22882183]]
Norm: 1.0
Deviation from I of qtq: 2.88912903322e-16
Qtq allclose to I? True
Eigenvalues of qtq: [ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
Determinant of qtq: 0.9999999999999997
